// WARNING: Do not edit this file manually. Auto-generated by remstyle.
export const apple_vercel_theme = {
  version: 1,
  themeName: "Vercel Apple Minimalist V1.0",
  palette: {
    bg: "#F2F4F7", // Soft light-gray background
    surface: "#FFFFFF", // Pure stark white card surface
    border: "#E2E8F0", // Very low-contrast, subtle border
    fg: "#0F172A", // Dark charcoal for primary text (not pure black)
    fgMuted: "#64748B", // Medium gray for secondary text/icons
    accent: "#0070F3", // Vibrant electric Vercel blue
  },
  typography: {
    sans: "Inter", // Clean, geometric sans-serif (or Geist/SF Pro)
    mono: "JetBrains Mono",
    scale: {
      hero: 96,
      headline: 32,
      body: 16,
      code: 14,
    },
  },
  spatial: {
    radius: 24, // Heavy, soft rounding (compared to the 0px/8px of industrial)
    borderWidth: 1, // Thin, delicate borders
    padding: 24, // Airy, generous spacing
    elevation: "shadow" as const, // Triggers the soft diffused drop-shadow in your components
  },
};

export type VideoTheme = typeof apple_vercel_theme;
