// WARNING: Do not edit this file manually. Auto-generated by remstyle.
export const notion_ish_theme = {
  version: 1,
  themeName: "Academic Editorial V1.0",
  palette: {
    bg: "#F6F4F0", // Paper White background
    surface: "#FAFAF7", // Warm Off-White card surface
    border: "#D1D1D1", // Gray Border
    fg: "#2A2A2A", // Soft dark charcoal for high reading legibility
    fgMuted: "#737373", // Muted gray for default annotations
    accent: "#829C87", // Muted Sage Green (Action/Hover states)
  },
  typography: {
    serif: "Lora", // Elegant Serif for primary headlines
    sans: "Inter", // Clean Sans-Serif for body copy
    mono: "Fira Code", // Clean monospace for the Code Module Reference
    scale: {
      hero: 64,
      headline: 36, // Mapped directly from the 36pt scale
      subhead: 24, // Mapped directly from the 24pt scale
      body: 16, // Mapped directly from the 16pt scale
      code: 14,
    },
  },
  spatial: {
    radius: 8, // Soft, document-style rounded corners
    borderWidth: 1, // Subtle 1px gray border
    padding: 32, // Generous "comfortable" reading spacing
    elevation: "shadow" as const, // Very soft drop shadow to lift the paper card
  },
};

export type VideoTheme = typeof notion_ish_theme;
