// WARNING: Do not edit this file manually. Auto-generated by remstyle.
export const industrial_developer_theme = {
  version: 1,
  themeName: "Industrial Developer Design System V1.0",
  palette: {
    bg: "#1A1A1A", // Deep matte charcoal background
    surface: "#E3D5C0", // Canvas Tan surface
    border: "#2C2C2C", // Hard mathematical border (from hex provided)
    fg: "#FFFFFF", // White text for dark canvas areas
    fgMuted: "#2C2C2C", // Used for dark text on the light canvas surface
    accent: "#FF6600", // Utility Orange
  },
  typography: {
    sans: "Inter", // Geometric sans-serif
    mono: "JetBrains Mono", // Clean monospace for code blocks
    scale: {
      hero: 64,
      headline: 32, // Mapped directly from "HEADLINE 32px"
      body: 16, // Mapped directly from "BODY 16px"
      code: 14, // Mapped directly from "CODE 14px"
    },
  },
  spatial: {
    radius: 8, // Mapped directly from "PRECISION CORNER RADIUS R8"
    borderWidth: 1, // Sharp, precise border rendering
    padding: 8, // Mapped directly from the "8px" Spacing Grid
    elevation: "flat" as const, // High contrast, flat lighting with no drop shadow
  },
};

export type VideoTheme = typeof industrial_developer_theme;
