// WARNING: Do not edit this file manually. Auto-generated by remstyle.
export const blade_runner_theme = {
  version: 1,
  themeName: "Stripe Neon Tokyo V1.0",
  palette: {
    bg: "#0A0915", // Deep midnight purple/black background
    surface: "#121124", // Translucent dark charcoal/purple surface
    border: "#BC00DD", // Glowing neon magenta/purple border edge
    fg: "#FFFFFF", // Stark white for high readability headlines
    fgMuted: "#00E5FF", // Cyber phosphor cyan for secondary text and accents
    accent: "#FF007F", // Hot magenta for buttons and primary CTA chips
  },
  typography: {
    sans: "Orbitron", // Futuristic, geometric sans-serif
    mono: "Fira Code", // Clean developer mono with ligatures
    scale: {
      hero: 96,
      headline: 32,
      body: 16,
      code: 14,
    },
  },
  spatial: {
    radius: 12, // Balanced, sharp-but-precise corners
    borderWidth: 1.5, // Slightly pronounced border to catch the color
    padding: 20, // Tight mathematical grid layout
    elevation: "shadow" as const,
    neonGlow: "0px 0px 15px rgba(188, 0, 221, 0.4)", // Custom property hook for the component box-shadow drop
  },
};

export type VideoTheme = typeof blade_runner_theme;
